<?php
namespace lighter\handlers;


use lighter\views\HttpMessage;
use lighter\views\View;


/**
 * represent a HttpResponse, so handle the http response header AND the http response
 * body, i.e. the webpage content.
 *
 * This class has been writed in regard of the HTTP RFC 2616.
 * See http://www.w3.org/Protocols/rfc2616/rfc2616.html
 *
 * @name HttpResponse
 * @package lighter
 * @subpackage handlers
 * @see lighter\handlers\HttpRequest
 * @since 0.1
 * @version 0.1
 * @author Michel Begoc
 * @copyright (c) 2011 Michel Begoc
 * @license MIT - see http://www.opensource.org/licenses/mit-license.php
 *
 */
class HttpResponse {
    /**
     * the single instance<
     *
     * @var handlers\HttpReponse
     */
    private static $instance = null;
    /**
     * the body of the HTTP response. It's a view which will produce it.
     *
     * @var views\View
     */
    private $body = null;
    /**
     * default HTTP messages, as described  by RFC 2616
     *
     * @var array
     */
    private $httpMessages;
    /**
     * the HTTP code which need a HTTP body, as described by RFC 2616
     *
     * @var unknown_type
     */
    private $httpBodyCodes;
    /**
     * The code of this response
     *
     * @var int - default 200
     */
    private $code = 200;
    /**
     * the content type of the response
     *
     * @var string - default text/html
     */
    private $contentType = 'text/html';


    /**
     * construct a new HttpResponse
     */
    private function __construct() {
        $this->httpMessages = array(
            100 => 'Continue',
            101 => 'Switching Protocols',

            200 => 'OK',
            201 => 'Created',
            202 => 'Accepted',
            203 => 'Non-Authoritative Information',
            204 => 'No content',
            205 => 'Reset Content',
            206 => 'Partial Content',

            300 => 'Multiple Choices',
            301 => 'Moved Permanently',
            302 => 'Found',
            303 => 'See Other',
            304 => 'Not Modified',
            305 => 'Use Proxy',
            306 => '(Unused)',
            307 => 'Temporary Redirect',

            400 => 'Bad Request',
            401 => 'Unauthorized',
            402 => 'Payment Required',
            403 => 'Forbidden',
            404 => 'Not found',
            405 => 'Method Not Allowed',
            406 => 'Not Acceptable',
            407 => 'Proxy Authentication Required',
            408 => 'Request Timeout',
            409 => 'Conflict',
            410 => 'Gone',
            411 => 'Length Required',
            412 => 'Precondition Failed',
            413 => 'Request Entity Too Large',
            414 => 'Request-URI Too Long',
            415 => 'Unsupported Media Type',
            416 => 'Requested Range Not Satisfiable',
            417 => 'Excpectation Failed',

            500 => 'Internal server error',
            501 => 'Not Implemented',
            502 => 'Bad Gateway',
            503 => 'Service Unavailable',
            504 => 'Gateway Timeout',
            505 => 'HTTP Version Not Supported'
        );

        $this->httpBodyCodes = array(100, 101, 200,  201, 202, 203, 206);
        $this->contentType = HttpRequest::getInstance()->getAccept();
    }


    /**
     * manage the singleton
     *
     * @return lighter\handlers\HttpResponse
     */
    public static function getInstance() {
        if (!isset(self::$instance)) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * set the http code for this response
     *
     * @param int $code
     * @throws HttpException
     */
    public function setCode($code) {
        if (isset($this->httpMessages[$code])) {
            $this->code = (int)$code;
        }else{
            throw new HttpException(_('Invalid HTTP code'));
        }
    }


    /**
     * return the http code of this response
     *
     * @return int
     */
    public function getCode() {
        return $this->code;
    }


    /**
     * set the body of the response, wich is generated by a View
     *
     * @param views\View $view
     */
    public function setBody(View $view) {
        $this->body = $view;
    }


    /**
     * send this response, i.e. write it to the output stream
     */
    public function send() {
        $this->prepareHeader();
        if ($this->code >= 200 && $this->code < 300) {
            if ($this->body != null) {
                if (in_array($this->code, $this->httpBodyCodes)) {
                    if ($this->body->isSupportedMimeType($this->contentType)) {
                        $this->body->display($this->contentType);
                    } else {
                        $this->body->getDefaultMimeType();
                        if ($this->body->getDefaultMimeType() != null) {
                            $this->contentType = $this->body->getDefaultMimeType();
                            $this->prepareHeader();
                            $this->body->display($this->contentType);
                        } else {
                            $this->code = 406;
                            $this->displayHttpError();
                        }
                    }
                }
            } else {
                $this->code = 500;
                $this->displayHttpError();
            }
        } else {
            $this->displayHttpError();
        }
    }


    protected function displayHttpError() {
        $httpMessage = new HttpMessage($this->code, $this->httpMessages[$this->code]);
        if (!$httpMessage->isSupportedMimeType($this->contentType)) {
            $this->contentType = $httpMessage->getDefaultMimeType();
        }
        $this->prepareHeader();
        $httpMessage->display($this->contentType);
    }


    /**
     * prepare the http header
     */
    private function prepareHeader() {
        $string = 'HTTP/1.1 '.$this->code.' '.$this->httpMessages[$this->code];
        header($string);
        header('Content-Type: '.$this->contentType);
    }

}

